SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

CREATE DATABASE IF NOT EXISTS testsql CHARACTER SET utf8 COLLATE utf8_general_ci;
DROP USER IF EXISTS 'test'@'%';
CREATE USER IF NOT EXISTS 'test'@'%' IDENTIFIED BY 'test';
USE testsql;
GRANT ALL PRIVILEGES ON *.* TO 'test'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;





/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE IF NOT EXISTS test (
  id int,
  texte varchar(50)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

INSERT INTO test VALUES
(1, 'gfdsg'),
(2, 'fgsdfgs');



CREATE USER 'test1'@'localhost' IDENTIFIED BY 'test';
USE testsql;
GRANT ALL PRIVILEGES ON ffvldecollage.* TO 'test1'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
COMMIT;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
